CREATE TABLE IF NOT EXISTS logs (
    id INTEGER NOT NULL,
    type TEXT NOT NULL,
    message TEXT NOT NULL,
    tb TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);